# http://ezbookkeeping.mayswind.net/zh_Hans/installation
# http://ezbookkeeping.mayswind.net/demo/docker-compose.yml

---
services:
  db:
    image: mariadb:11.4.2
    container_name: ezbookkeeping_db
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 25aaa363fc24a3c5f6045e05
      MYSQL_DATABASE: ezbookkeeping
      MYSQL_USER: ezbookkeeping
      MYSQL_PASSWORD: ezbookkeeping
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db_data:/var/lib/mysql
      - ./db_log:/var/log/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ezbookkeeping

  ezbookkeeping:
    image: mayswind/ezbookkeeping:1.1.1
    container_name: ezbookkeeping
    hostname: ezbookkeeping
    restart: unless-stopped
    ports:
      - 8081:8080
    environment:
      TZ: Asia/Shanghai
      EBK_SERVER_DOMAIN: ezbookkeeping.honeok.com
      EBK_SERVER_ENABLE_GZIP: true
      EBK_MCP_ENABLE_MCP: true
      EBK_DATABASE_TYPE: mysql
      EBK_DATABASE_HOST: db:3306
      EBK_DATABASE_NAME: ezbookkeeping
      EBK_DATABASE_USER: ezbookkeeping
      EBK_DATABASE_PASSWD: ezbookkeeping
      EBK_LOG_MODE: file
      EBK_SECURITY_SECRET_KEY: 0ab78c51dbf12dd9884fd020f1be73b38217ea3f20f6ccab850aae5dd167fce8 # openssl rand -hex 32
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./ez_storage:/ezbookkeeping/storage
      - ./ez_log:/ezbookkeeping/log
    depends_on:
      db:
        condition: service_healthy
    networks:
      - ezbookkeeping

networks:
  ezbookkeeping:
    driver: bridge
