---
log:
  level: warn
  format: json
  output: none

metrics:
  addr: :9000
  path: /metrics

services:
  # TCP转发
  - name: DMIT
    addr: :30000
    handler:
      type: rtcp
    listener:
      type: rtcp
    forwarder:
      nodes:
      - name: DMIT
        addr: 1.1.1.1:38438
    metrics: true

  # UDP转发
  - name: Bandwagon
    addr: :30001
    handler:
      type: rudp
    listener:
      type: rudp
      metadata:
        keepAlive: true      # 每一个客户端对应一条转发通道, 当keepalive参数设置为false时, 请求的响应数据返回给客户端后会立即关闭通道连接
        ttl: 5s              # 同时也是UDP数据包大小的上限, 如果数据包大小超过此设定值数据会被截断
        readBufferSize: 4096 # UDP读缓冲区大小, 同时也是UDP数据包大小的上限, 如果数据包大小超过此设定值数据会被截断
    forwarder:
      nodes:
      - name: Bandwagon
        addr: 8.8.8.8:38438
    metrics: true
