services:
  nginx:
    image: honeok/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/certs:/etc/nginx/certs
      - $PWD/html:/usr/share/nginx/html
      - $PWD/log:/var/log/nginx
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=256m
    network_mode: bridge