services:
  openresty:
    image: honeok/openresty
    container_name: openresty
    restart: unless-stopped
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - $PWD/conf.d:/etc/nginx/conf.d
      - $PWD/certs:/etc/nginx/certs
      - $PWD/html:/usr/local/openresty/nginx/html
      - $PWD/log:/usr/local/openresty/nginx/logs
    tmpfs:
      - /var/cache/openresty:rw,noexec,nosuid,size=256m
    network_mode: bridge