# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2025 honeok <i@honeok.com>

## variables
# general
DOCKER_USERNAME       := honeok
DOCKER_REPO           := openresty
DOCKER_BUILD_ARGS     := --no-cache --progress=plain
PLATFORMS             := linux/amd64,linux/arm64
