---
services:
  danmakurender:
    image: honeok/danmakurender
    container_name: danmakurender
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs
    network_mode: bridge
