---
## 全局配置
metadata:
  logging: # 日志设置
    level: info # debug info warn error
    output: /var/log/gost/gost.log
    format: json # json/text
  dns: # DNS设置
    addr: 223.5.5.5 # DNS服务器
    ttl: 3600 # 缓存时间 (秒)
  trace: false # 启用请求追踪
  timeout: 30s # 全局超时

## 服务列表
services:

# TCP转发
- name: DMIT
  addr: :30000
  handler:
    type: rtcp
  listener:
    type: rtcp
  forwarder:
    nodes:
    - name: Juhost
      addr: 1.1.1.1:38438

# UDP转发
- name: Bandwagon
  addr: :30001
  handler:
    type: rudp
  listener:
    type: rudp
  forwarder:
    nodes:
    - name: Bandwagon
      addr: 8.8.8.8:38438

## 绕过规则
bypasses:
  - name: local-bypass
    matcher:
      ip:
        - 127.0.0.1/8
        - 192.168.0.0/16
      domain:
        - localhost
        - "*.local"

## DNS解析器
resolvers:
  - name: google-dns
    type: dns
    addr: 8.8.8.8
    timeout: 5s
  - name: doh
    type: doh
    addr: https://dns.google/dns-query
