---
name: 'Build and Publish Caddy'

on:
  schedule:
    - cron: '0 16 * * 3,6'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  DOCKER_USERNAME: ${{ github.repository_owner }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    name: 'Build and Publish Stable Caddy'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        run: |
          CADDY_LVER="$(wget -qO- --tries=50 --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/caddyserver/caddy/releases/latest | grep '"tag_name":' | sed -n 's/.*"tag_name": "v\([^"]*\)".*/\1/p')"
          CADDY_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/caddy/tags 2>/dev/null | grep -o '"name":"[^"]*"' | awk -F'"' '{print $4}' | grep -v 'alpine' | sort -Vr | head -n1 || true)"
          CADDY_ALPINE_LVER="$(docker run --rm caddy:${CADDY_LVER}-alpine 2>/dev/null sh -c 'caddy version 2>&1' | sed -n 's/^v\([0-9.]*\).*/\1/p' || true)"
          echo "CADDY_LVER=$CADDY_LVER" >> $GITHUB_ENV
          echo "CADDY_CVER=$CADDY_CVER" >> $GITHUB_ENV
          if [[ ( "$(echo -e "$CADDY_LVER\n$CADDY_CVER" | sort -V | head -n1)" != "$CADDY_LVER" && "$CADDY_ALPINE_LVER" == "$CADDY_LVER" ) || ( -z "$CADDY_CVER" && -n "$CADDY_ALPINE_LVER" ) ]]; then
            echo "IS_RENEW=1" >> $GITHUB_ENV
          fi

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and Push Caddy image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          context: ${{ github.workspace }}/ldnmp/caddy
          file: ${{ github.workspace }}/ldnmp/caddy/Dockerfile
          platforms: linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          build-args: CADDY_LVER=${{ env.CADDY_LVER }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/caddy:${{ env.CADDY_LVER }}-alpine
            ${{ env.DOCKER_USERNAME }}/caddy:${{ env.CADDY_LVER }}
          push: true