---
name: 'Sync contributors'

on:
  schedule:
    - cron: '0 16 * * 6'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  sync_readme:
    name: 'Sync contributors to github'
    runs-on: ubuntu-latest
    outputs:
      update_readme: ${{ steps.compare.outputs.update_readme }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          ref: release
          fetch-depth: 0

      - name: 'Comparing contributors'
        id: compare
        run: |
          OFFICIAL="$(wget -qO- https://github.com/nezhahq/nezha/raw/master/README.md | sed -n '/<!--GAMFC_DELIMITER-->/,/<!--GAMFC_DELIMITER_END-->/p')"
          LOCAL="$(sed -n '/<!--GAMFC_DELIMITER-->/,/<!--GAMFC_DELIMITER_END-->/p' ./README.md)"
          if [ "$OFFICIAL" != "$LOCAL" ]; then
            printf '%s\n' "$OFFICIAL" | sed -i '/<!--GAMFC_DELIMITER-->/,/<!--GAMFC_DELIMITER_END-->/{
              /<!--GAMFC_DELIMITER-->/r /dev/stdin
              /<!--GAMFC_DELIMITER-->/,/<!--GAMFC_DELIMITER_END-->/d
            }' ./README.md
            echo "update_readme=1" >> "$GITHUB_OUTPUT"
          fi

      - name: 'Upload commit to repository'
        uses: stefanzweifel/git-auto-commit-action@v6
        if: steps.compare.outputs.update_readme == 1
        with:
          commit_message: "docs: sync contributors by github actions"
          branch: release

  sync_dockerhub:
    name: 'Sync readme to dockerhub'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ github.repository_owner }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    needs:
      - sync_readme
    if: needs.sync_readme.outputs.update_readme == 1

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v5
        with:
          ref: release
          fetch-depth: 0

      - name: 'Sync README to dockerhub'
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_USERNAME }}/nezha-dashboard
          readme-filepath: ./README.md
          enable-url-completion: false
