---
name: 'Build and Publish Openresty'

on:
  schedule:
    - cron: '0 16 * * 3,6'
  workflow_dispatch:

jobs:
  build:
    name: 'Build and Publish Openresty'
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: 'Fetch Versions and Determine Build'
        run: |
          RESTY_CVER="$(wget -qO- --tries=50 https://hub.docker.com/v2/repositories/honeok/openresty/tags 2>/dev/null | jq -r ".results // [] | .[].name" | grep -v '^alpine$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "")"
          RESTY_LVER="$(wget -qO- --tries=50 https://api.github.com/repos/openresty/openresty/tags | grep '"name":' | sed -E 's/.*"name": *"([^"]+)".*/\1/' | sort -Vr | head -n1 | sed 's/v//')"
          ZSTD_LVER="$(wget -qO- --tries=50 https://api.github.com/repos/facebook/zstd/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/v//')"
          RESTY_ALPINE_LVER="$(docker run --rm nginx:"${RESTY_LVER}-alpine" sh -c "nginx -v 2>&1 | awk -F'/' '{print \$NF}'")"
          RESTY_ALPINE_TAG="$(docker run --rm nginx:"${RESTY_LVER}-alpine" sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')"
          echo "RESTY_CVER=$RESTY_CVER" >> $GITHUB_ENV
          echo "RESTY_LVER=$RESTY_LVER" >> $GITHUB_ENV
          echo "ZSTD_LVER=$ZSTD_LVER" >> $GITHUB_ENV
          echo "RESTY_ALPINE_LVER=$RESTY_ALPINE_LVER" >> $GITHUB_ENV
          echo "RESTY_ALPINE_TAG=$RESTY_ALPINE_TAG" >> $GITHUB_ENV
          if [[ ("$(echo -e "$RESTY_LVER\n$RESTY_CVER" | sort -V | head -n1)" != "$RESTY_LVER" && "$RESTY_ALPINE_LVER" == "$RESTY_LVER") || (-z "$RESTY_CVER" && -n "$RESTY_ALPINE_LVER" && -n "$RESTY_ALPINE_TAG") ]]; then
            echo "IS_RENEW=1" >> $GITHUB_ENV
          fi

      - name: 'Set up Docker QEMU'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/setup-buildx-action@v3.11.1

      - name: 'Login to DockerHub'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: 'Build and Push Openresty Image'
        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6.18.0
        with:
          context: ${{ github.workspace }}/ldnmp/openresty
          file: ${{ github.workspace }}/ldnmp/openresty/Dockerfile
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
          build-args: |
            RESTY_LVER=${{ env.RESTY_LVER }}
            ZSTD_LVER=${{ env.ZSTD_LVER }}
          tags: |
            ${{ env.DOCKER_USERNAME }}/openresty:alpine
            ${{ env.DOCKER_USERNAME }}/openresty:${{ env.RESTY_LVER }}-alpine
            ${{ env.DOCKER_USERNAME }}/openresty:${{ env.RESTY_LVER }}-alpine${{ env.RESTY_ALPINE_TAG }}
          push: true