---
name: 'Release nezha-dashboard'

on:
  push:
    tags:
      - 'v*'
  schedule:
    - cron: '0 16 1 * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}

jobs:
  release:
    name: 'Release nezha-dashboard'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        NEZHA_VERSION:
          - 'v0.18.6'
          - 'v0.20.13'

    steps:
      - name: 'Clone source code and fetch ipinfo geoip db'
        run: |
          cd ${{ github.workspace }}/v0
          git clone --depth=1 --branch ${{ matrix.NEZHA_VERSION }} https://github.com/nezhahq/nezha.git ./${{ matrix.NEZHA_VERSION }}
          cd ${{ matrix.NEZHA_VERSION }} || exit 1
          rm -f pkg/geoip/geoip.db
          wget --tries=50 -qO pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
      
      - name: 'Build binaries with xgo'
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.21
          dest: build
          pkg: cmd/dashboard
          prefix: dashboard
          targets: linux/amd64,linux/armv6,linux/armv7,linux/arm64,linux/s390x
          v: true
          x: false
          race: false
          tags: timetzdata
          ldflags: -s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${{ matrix.NEZHA_VERSION }}
          buildmode: default
          trimpath: true

      - name: Fix dist artifact name
        run: |
          ls -al dist/
          mv dist/dashboard-linux-arm-7 dist/dashboard-linux-arm

      - name: Compress release assets
        run: |
          cd dist
          for file in *; do
            if [ -f "$file" ]; then
              zip "${file}.zip" "$file"
            fi
          done
          cd ..

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"
          generateReleaseNotes: true