name: 'Delete old workflow runs'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: 'Delete workflow runs'
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          dry_run: true