---
name: 'Sync Docker Install Script'

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write

jobs:
  sync:
    name: 'Sync Docker Install Script'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v5
        with:
          ref: master
          fetch-depth: 0

      - name: 'Download and compare install-docker.sh'
        working-directory: ${{ github.workspace }}/docker
        run: |
          curl -Lso install-docker.new https://get.docker.com
          if ! cmp -s install-docker.new install-docker.sh; then
            mv -f install-docker.new install-docker.sh
            echo "IS_RENEW=1" >> $GITHUB_ENV
          fi

      - name: 'Upload commit to repository'
        uses: stefanzweifel/git-auto-commit-action@v6
        if: env.IS_RENEW == 1
        with:
          commit_message: "chore: bump script version by github actions"
          branch: master