name: 'Cross arch docker run test'

on:
  workflow_dispatch:

jobs:
  test:
    name: 'Cross arch docker run test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Run 386 container'
        run: |
          docker pull --platform linux/386 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/386 \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run amd64 container'
        run: |
          docker pull --platform linux/amd64 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/amd64 \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run armv6 container'
        run: |
          docker pull --platform linux/arm/v6 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/arm/v6 \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run armv7 container'
        run: |
          docker pull --platform linux/arm/v7 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform llinux/arm/v7 \
            --network=host \
            pakho611/3x-ui:latest || true
      - name: 'Run amd64 container'
        run: |
          docker pull --platform linux/amd64 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/amd64 \
            --network=host \
            pakho611/3x-ui:latest || true
      - name: 'Run arm64 container'
        run: |
          docker pull --platform linux/arm64 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/arm64 \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run ppc64le container'
        run: |
          docker pull --platform linux/ppc64le pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/ppc64le \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run riscv64 container'
        run: |
          docker pull --platform linux/riscv64 pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/riscv64 \
            --network=host \
            pakho611/3x-ui:latest || true

      - name: 'Run s390x container'
        run: |
          docker pull --platform linux/s390x pakho611/3x-ui:latest
          timeout 10s docker run --rm --platform linux/s390x \
            --network=host \
            pakho611/3x-ui:latest || true