name: 'Cross arch docker run test'

on:
  workflow_dispatch:

jobs:
  test:
    name: 'Cross arch docker run test'
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v4.2.2

      - name: 'Set up Docker QEMU'
        uses: docker/setup-qemu-action@v3.6.0

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3.10.0

      - name: 'Run amd64 container'
        run: |
          docker pull --platform linux/amd64 honeok/x-ui:latest
          timeout 10s docker run --rm --platform linux/amd64 \
            --network=host \
            --cap-add=NET_ADMIN \
            honeok/x-ui:latest || true

      - name: 'Run arm64 container'
        run: |
          docker pull --platform linux/arm64 honeok/x-ui:latest
          timeout 10s docker run --rm --platform linux/arm64 \
            --network=host \
            --cap-add=NET_ADMIN \
            honeok/x-ui:latest || true

      - name: 'Run s390x container'
        run: |
          docker pull --platform linux/s390x honeok/x-ui:latest
          timeout 10s docker run --rm --platform linux/s390x \
            --network=host \
            --cap-add=NET_ADMIN \
            honeok/x-ui:latest || true